In [1]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import scipy.stats as scs
import math
import warnings

In [2]:
df1=pd.read_pickle("subscribers.dms")
df1.loc[df1['revenue_net']>0]

,subid,package_type,num_weekly_services_utilized,preferred_genre,intended_use,weekly_consumption_hour,num_ideal_streaming_services,retarget_TF,age,male_TF,...,creation_until_cancel_days,cancel_before_trial_end,trial_end_date,initial_credit_card_declined,revenue_net,join_fee,language,paid_TF,refund_after_trial_TF,payment_type
192823,29726122,base,2.049135,comedy,access to exclusive content,20.051667,1.860289,False,61.0,False,...,NaN,True,2020-03-05,False,4.5875,0.3303,ar,True,False,Standard Charter
315863,20299962,base,3.002048,drama,access to exclusive content,34.551230,1.870503,False,23.0,False,...,NaN,True,2020-03-20,False,3.4498,0.0000,ar,True,False,RAKBANK
99989,21191741,NaN,NaN,NaN,expand regional access,34.551230,NaN,False,53.0,True,...,158.0,True,2019-07-26,False,9.2117,0.0367,ar,True,False,Standard Charter
208223,21511732,enhanced,2.320133,comedy,replace OTT,27.301448,1.849591,True,26.0,False,...,153.0,True,2019-11-26,False,3.2296,0.0367,ar,True,False,RAKBANK
7506,29576692,NaN,3.012358,NaN,expand international access,34.551230,1.927293,False,31.0,False,...,56.0,True,2019-07-28,False,1.6148,0.0367,ar,True,True,Standard Charter
179332,21447938,base,2.788487,drama,replace OTT,30.201361,1.860907,False,59.0,False,...,NaN,True,2020-01-04,False,4.5875,0.3303,ar,True,False,RAKBANK
161,27843327,base,NaN,regional,replace OTT,27.301448,NaN,False,48.0,False,...,NaN,True,2019-09-11,False,13.7992,0.0367,ar,True,False,Najim
110387,21528505,NaN,NaN,NaN,expand regional access,31.651317,NaN,False,35.0,True,...,NaN,True,2019-08-25,False,15.6342,0.0367,ar,True,False,CBD
194415,26461912,enhanced,4.314329,comedy,supplement OTT,25.851492,2.372655,False,20.0,False,...,NaN,True,2020-03-11,False,4.8811,0.0367,ar,True,False,Standard Charter
40718,25698109,NaN,NaN,NaN,expand regional access,30.201361,NaN,False,63.0,False,...,282.0,True,2019-07-19,False,4.5875,0.0367,ar,True,False,Standard Charter
219167,22400953,base,2.773759,comedy,access to exclusive content,21.501623,1.854392,False,31.0,False,...,NaN,True,2020-02-12,False,5.0279,0.0000,ar,True,False,Standard Charter
55515,25100145,enhanced,2.439432,comedy,access to exclusive content,27.301448,1.902363,False,60.0,False,...,NaN,True,2019-09-17,False,4.5875,0.0367,ar,True,False,RAKBANK
150317,28506369,enhanced,2.850348,regional,replace OTT,30.201361,1.855627,False,46.0,True,...,NaN,True,2019-12-24,False,10.0191,0.0367,ar,True,False,RAKBANK
243070,20783123,base,3.731093,drama,access to exclusive content,28.751405,2.343164,True,60.0,False,...,NaN,True,2020-01-23,False,9.2117,0.0367,ar,True,False,Standard Charter
16830,26156384,NaN,2.411448,NaN,expand international access,21.501623,1.857341,False,51.0,False,...,NaN,True,2019-07-19,False,13.7992,0.0000,ar,True,False,RAKBANK
258896,20733152,economy,2.741359,comedy,access to exclusive content,28.751405,1.970636,False,51.0,False,...,NaN,True,2020-03-06,False,4.5875,0.0367,ar,True,False,Paypal
196979,26795774,base,2.700120,comedy,supplement OTT,28.751405,1.887105,False,38.0,False,...,NaN,True,2020-04-09,False,4.5875,0.3303,ar,True,False,Standard Charter
287877,21866281,enhanced,NaN,drama,access to exclusive content,34.551230,NaN,False,41.0,True,...,NaN,True,2020-04-09,False,4.5875,0.3303,ar,True,False,Paypal
271936,25630872,base,4.753228,NaN,NaN,28.751405,2.795314,False,37.0,False,...,NaN,True,2020-02-21,False,4.5875,0.3303,ar,True,False,Standard Charter
104582,25644417,NaN,2.367263,NaN,expand regional access,25.851492,1.870439,False,48.0,False,...,NaN,True,2019-07-16,False,4.5875,0.0367,ar,True,False,Paypal
278662,24102724,base,NaN,comedy,access to exclusive content,30.201361,NaN,False,49.0,False,...,63.0,True,2020-03-23,False,1.9451,0.0367,ar,True,True,Standard Charter
202850,25027288,base,2.658881,drama,access to exclusive content,21.501623,1.901508,False,57.0,False,...,NaN,True,2019-10-27,False,9.8356,0.0367,ar,True,False,RAKBANK
273812,28886107,enhanced,NaN,comedy,access to exclusive content,22.951579,NaN,False,52.0,False,...,NaN,True,2020-03-02,False,4.8444,0.0367,ar,True,False,Paypal
82877,29998133,NaN,4.290759,NaN,expand regional access,28.751405,2.296941,False,39.0,False,...,NaN,True,2019-07-27,False,11.0467,0.0367,ar,True,False,Standard Charter
94286,26716687,NaN,4.108134,NaN,expand regional access,27.301448,2.314088,False,44.0,False,...,NaN,True,2019-07-26,False,1.0276,0.0000,ar,True,False,Standard Charter
40604,28078576,NaN,2.720740,NaN,education,30.201361,1.896226,True,42.0,False,...,NaN,True,2019-07-27,False,2.7158,0.0000,ar,True,False,Paypal
187720,24318218,base,NaN,comedy,supplement OTT,30.201361,NaN,False,58.0,True,...,NaN,True,2020-03-28,False,4.5875,0.3303,ar,True,False,Najim
137317,23179924,base,NaN,comedy,access to exclusive content,33.101274,NaN,True,42.0,False,...,NaN,True,2020-01-02,False,9.2117,0.3303,ar,True,False,RAKBANK
99153,25806271,NaN,3.009412,NaN,expand regional access,24.401536,1.795414,False,58.0,False,...,NaN,True,2019-08-21,False,9.1750,0.0367,ar,True,False,Paypal
72146,24821451,enhanced,NaN,other,access to exclusive content,36.001186,NaN,True,60.0,True,...,NaN,True,2020-02-29,False,4.8811,0.1101,ar,True,False,Paypal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
141732,22403327,enhanced,3.996200,drama,access to exclusive content,33.101274,2.460437,False,57.0,False,...,NaN,True,2019-11-17,False,9.2117,0.0367,ar,True,False,Standard Charter
105480,25937903,base,NaN,comedy,access to exclusive content,28.751405,NaN,False,69.0,False,...,NaN,True,2019-09-28,False,15.0837,0.0367,ar,True,False,CBD
159226,26851116,enhanced,NaN,drama,access to exclusive content,22.951579,NaN,False,69.0,False,...,NaN,True,2020-02-22,False,4.5875,0.3303,ar,True,False,Paypal
133320,25306093,base,2.361372,international,access to exclusive content,27.301448,1.867833,False,55.0,False,...,202.0,True,2019-10-21,False,3.9269,0.0367,ar,True,False,Paypal
344874,27830586,economy,5.256931,international,access to exclusive content,40.351055,2.528470,False,62.0,True,...,NaN,True,2020-04-03,False,4.5875,0.3303,ar,True,False,Standard Charter
11003,21158019,NaN,NaN,NaN,expand regional access,25.851492,NaN,False,58.0,False,...,NaN,True,2019-07-15,False,9.7255,0.0367,ar,True,False,Paypal
326982,21069614,base,4.069841,comedy,access to exclusive content,30.201361,2.493012,False,48.0,False,...,NaN,True,2020-03-07,False,4.7343,0.6606,ar,True,False,CBD
109293,21945688,NaN,4.468975,NaN,expand regional access,28.751405,2.473709,False,74.0,False,...,NaN,True,2019-08-25,False,4.5875,0.0367,ar,True,False,Standard Charter
12435,27191430,NaN,2.876858,NaN,expand regional access,27.301448,1.965287,False,52.0,False,...,NaN,True,2019-07-16,False,4.5875,0.0367,ar,True,False,RAKBANK
200820,22521900,economy,NaN,drama,access to exclusive content,30.201361,NaN,False,60.0,False,...,NaN,True,2020-02-22,False,4.5875,0.1101,ar,True,False,Standard Charter
175155,23532424,base,2.977010,comedy,replace OTT,36.001186,1.879013,False,31.0,True,...,NaN,True,2020-01-06,False,4.9545,0.0000,ar,True,False,Standard Charter
130010,20588003,base,2.538110,drama,access to exclusive content,25.851492,1.684862,False,60.0,False,...,NaN,True,2019-12-09,False,6.4225,0.0000,ar,True,False,Standard Charter
225428,25341091,enhanced,2.435013,drama,replace OTT,24.401536,1.835121,False,59.0,False,...,NaN,True,2019-12-11,False,9.2117,0.6606,ar,True,False,Standard Charter
93382,27110337,enhanced,4.432154,international,supplement OTT,24.401536,2.326845,False,20.0,False,...,NaN,True,2019-09-08,False,4.5875,0.0000,ar,True,False,Standard Charter
184528,29072415,base,5.793032,drama,access to exclusive content,31.651317,2.602399,False,46.0,False,...,NaN,True,2019-10-26,False,3.2296,0.0000,ar,True,False,Najim
225965,26829242,economy,NaN,comedy,replace OTT,37.451142,NaN,False,69.0,True,...,NaN,True,2019-11-03,False,4.5875,0.0367,ar,True,False,Standard Charter
33363,25424389,NaN,2.597023,NaN,expand international access,24.401536,1.939432,False,36.0,False,...,NaN,True,2019-07-22,False,5.0646,0.0000,ar,True,False,Standard Charter
33094,22166509,NaN,NaN,NaN,expand international access,27.301448,NaN,False,52.0,False,...,NaN,True,2019-08-04,False,5.0279,0.0367,ar,True,False,CBD
171311,21048077,enhanced,NaN,comedy,access to exclusive content,24.401536,NaN,False,30.0,False,...,153.0,True,2019-10-06,False,4.5875,0.0367,ar,True,False,Paypal
42579,23189569,NaN,2.520437,NaN,expand international access,28.751405,1.938197,False,28.0,False,...,NaN,True,2019-07-23,False,1.8350,0.0367,ar,True,False,Najim
207628,25749000,economy,2.926934,drama,supplement OTT,30.201361,1.856862,False,67.0,False,...,NaN,True,2019-11-30,False,7.3400,0.0367,ar,True,False,Paypal
33320,23516585,NaN,3.937287,NaN,expand international access,25.851492,1.944715,False,46.0,False,...,NaN,True,2019-08-16,False,10.3494,0.0367,ar,True,False,Standard Charter
338767,21934088,base,2.685618,international,replace OTT,28.751405,1.880690,False,30.0,False,...,NaN,True,2020-04-07,False,4.5875,0.1101,ar,True,False,Standard Charter
35318,28985855,NaN,4.172934,NaN,expand international access,27.301448,2.603905,False,25.0,False,...,151.0,True,2019-07-18,False,4.5875,0.0367,ar,True,False,Standard Charter
99888,29909208,NaN,2.324552,NaN,expand international access,25.851492,1.884191,False,19.0,False,...,NaN,True,2019-08-05,False,7.4134,0.0000,ar,True,False,RAKBANK
61453,26067054,base,2.507033,drama,replace OTT,27.301448,1.899624,False,55.0,False,...,NaN,True,2020-01-19,False,5.0279,0.0367,ar,True,False,Standard Charter
1384,25927672,NaN,2.935771,NaN,expand regional access,30.201361,1.958703,False,34.0,False,...,NaN,True,2019-08-09,False,4.5875,0.0367,ar,True,False,Standard Charter
157820,29190645,enhanced,2.764924,comedy,access to exclusive content,25.851492,1.981060,False,46.0,False,...,NaN,True,2020-03-17,False,4.5875,0.3303,ar,True,False,RAKBANK
60056,21731043,enhanced,2.287731,comedy,supplement OTT,28.751405,1.867903,False,55.0,False,...,NaN,True,2019-12-05,False,9.7622,0.0000,ar,True,False,Paypal
229587,25843074,enhanced,2.361370,comedy,replace OTT,27.301448,1.835189,True,49.0,False,...,NaN,True,2019-12-21,False,4.5875,0.3303,ar,True,False,Paypal

In [3]:
df1.columns

Index(['subid', 'package_type', 'num_weekly_services_utilized',
       'preferred_genre', 'intended_use', 'weekly_consumption_hour',
       'num_ideal_streaming_services', 'retarget_TF', 'age', 'male_TF',
       'country', 'attribution_technical', 'attribution_survey', 'op_sys',
       'months_per_bill_period', 'plan_type', 'monthly_price',
       'discount_price', 'account_creation_date', 'creation_until_cancel_days',
       'cancel_before_trial_end', 'trial_end_date',
       'initial_credit_card_declined', 'revenue_net', 'join_fee', 'language',
       'paid_TF', 'refund_after_trial_TF', 'payment_type'],
      dtype='object')

In [4]:
df2=pd.read_pickle("customer_service_reps.dms")
df2.isnull().sum()

customer_service_rep_id          0
subid                            0
current_sub_TF                   0
cancel_date                1354081
account_creation_date            0
num_trial_days                   0
trial_completed_TF               0
billing_channel                  0
revenue_net_1month               0
payment_period                   0
last_payment                     0
next_payment               1369360
renew                      1602396
dtype: int64

In [5]:
df2.shape

(2208643, 13)

In [6]:
df2.drop_duplicates(subset=['subid'],keep='last',inplace=True)
df2

,customer_service_rep_id,subid,current_sub_TF,cancel_date,account_creation_date,num_trial_days,trial_completed_TF,billing_channel,revenue_net_1month,payment_period,last_payment,next_payment,renew
7,36189811,25108574,False,NaT,2019-11-26 03:30:29,7,True,itunes,1.1377,3,2020-01-26 03:30:29,NaT,NaN
9,31174901,25914865,True,NaT,2020-03-19 01:20:25,14,True,itunes,1.1377,1,2020-04-02 01:20:25,NaT,NaN
11,32408758,28778936,True,NaT,2020-03-27 23:46:37,0,True,google,1.1377,1,2020-03-28 06:47:31,NaT,NaN
13,39370969,21481314,True,NaT,2020-03-27 23:09:18,0,True,google,1.1377,1,2020-03-28 05:09:22,NaT,NaN
15,38637729,24230000,True,NaT,2020-03-27 22:59:09,0,True,google,1.1377,1,2020-03-28 04:59:17,NaT,NaN
17,37537571,22111363,True,NaT,2020-03-27 22:38:36,0,True,google,1.1377,1,2020-03-28 04:38:39,NaT,NaN
19,31649550,26606371,True,NaT,2020-03-27 22:06:38,0,True,google,1.1377,1,2020-03-28 04:06:42,NaT,NaN
21,32585559,25421493,True,NaT,2020-03-27 20:53:17,0,True,google,1.1377,1,2020-03-28 03:53:23,NaT,NaN
23,39294567,24120196,True,NaT,2020-03-27 23:14:23,0,True,google,1.1377,1,2020-03-28 03:14:28,NaT,NaN
25,37336404,29409169,True,NaT,2020-03-27 21:08:55,0,True,google,1.1377,1,2020-03-28 03:09:03,NaT,NaN
27,37061900,20154887,True,NaT,2020-03-27 22:59:12,0,True,google,1.1377,1,2020-03-28 02:59:18,NaT,NaN
29,30552635,22657468,True,NaT,2020-03-27 21:46:25,0,True,google,1.1377,1,2020-03-28 02:46:44,NaT,NaN
31,38604226,24857015,True,NaT,2020-03-27 22:36:34,0,True,google,1.1377,1,2020-03-28 02:36:38,NaT,NaN
33,38500872,23157022,True,NaT,2020-03-27 21:22:08,0,True,google,0.7707,1,2020-03-28 02:22:11,NaT,NaN
35,32055139,27989418,True,NaT,2020-03-27 20:05:01,0,True,google,1.1377,1,2020-03-28 02:05:05,NaT,NaN
37,34506463,22152524,True,NaT,2020-03-27 22:03:14,0,True,google,1.1377,1,2020-03-28 02:03:19,NaT,NaN
39,36233737,28399941,True,NaT,2020-03-27 18:42:43,0,True,google,1.1377,1,2020-03-28 01:42:47,NaT,NaN
41,32945462,22581650,True,NaT,2020-03-27 18:38:40,0,True,google,0.7707,1,2020-03-28 01:38:46,NaT,NaN
43,35959392,20381821,True,NaT,2020-03-27 20:35:10,0,True,google,1.1377,1,2020-03-28 01:35:14,NaT,NaN
45,38265006,29807830,True,NaT,2020-03-27 18:27:30,0,True,google,0.7707,1,2020-03-28 01:27:35,NaT,NaN
47,30548142,29441421,True,NaT,2020-03-27 19:13:50,0,True,google,1.1377,1,2020-03-28 01:13:54,NaT,NaN
49,36400614,25816074,True,NaT,2020-03-27 20:10:34,0,True,google,1.1377,1,2020-03-28 01:10:40,NaT,NaN
51,30235492,21641072,True,NaT,2020-03-27 20:55:14,0,True,google,1.1377,1,2020-03-28 00:55:18,NaT,NaN
53,32080209,29343633,True,NaT,2020-03-27 20:42:13,0,True,google,1.1377,1,2020-03-28 00:42:18,NaT,NaN
55,35027695,25833724,True,NaT,2020-03-27 19:28:34,0,True,google,1.1377,1,2020-03-28 00:28:40,NaT,NaN
57,38296791,22072206,True,NaT,2020-03-27 20:25:47,0,True,google,1.1377,1,2020-03-28 00:25:53,NaT,NaN
59,31856201,26147562,True,NaT,2020-03-27 20:09:04,0,True,google,1.1377,1,2020-03-28 00:09:09,NaT,NaN
60,33513851,28948735,False,2020-04-06 19:21:05,2020-03-27 23:59:39,14,False,OTT,0.0000,0,2020-03-27 23:59:39,NaT,False
61,30034436,21697364,False,2020-04-08 13:16:39,2020-03-27 23:59:06,14,False,OTT,0.0000,0,2020-03-28 00:05:20,NaT,False
63,31856201,27800927,True,NaT,2020-03-27 23:59:04,14,True,OTT,4.5875,1,2020-04-11 11:05:24,NaT,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2248355,39294567,26959015,True,NaT,2019-06-30 00:02:17,14,True,OTT,5.6518,2,2020-03-13 10:05:27,NaT,NaN
2248357,34246054,24911314,False,NaT,2019-06-30 00:02:00,14,True,OTT,4.5875,1,2019-07-14 10:43:57,NaT,False
2248360,31230756,27609410,True,NaT,2019-06-30 00:01:58,14,True,OTT,5.8353,2,2020-03-13 19:27:38,NaT,NaN
2248364,36080216,27196054,True,NaT,2019-06-30 00:01:56,14,True,OTT,4.5875,3,2020-03-13 14:01:42,NaT,False
2248365,34685812,23179152,False,2019-07-10 21:09:46,2019-06-30 00:01:53,14,False,OTT,0.0000,0,2019-06-30 01:05:31,NaT,NaN
2248369,30967722,26531005,True,NaT,2019-06-30 00:01:45,14,True,OTT,3.4498,3,2020-03-13 11:05:22,NaT,False
2248372,32101596,27140449,True,NaT,2019-06-30 00:01:43,14,True,OTT,5.6518,2,2020-03-13 11:05:23,NaT,NaN
2248373,32309638,28298577,False,2019-07-06 15:19:20,2019-06-30 00:01:42,14,False,OTT,0.0000,0,2019-06-30 00:01:42,NaT,NaN
2248374,36362730,21071284,False,2019-07-12 04:04:56,2019-06-30 00:01:35,14,False,OTT,0.0000,0,2019-06-30 00:01:35,NaT,NaN
2248375,35186000,28874372,False,2019-07-03 21:28:30,2019-06-30 00:01:34,14,False,OTT,0.0000,0,2019-06-30 00:01:34,NaT,NaN
2248376,34000200,23633096,False,2019-06-30 10:01:02,2019-06-30 00:01:32,14,False,OTT,0.0000,0,2019-06-30 00:01:32,NaT,NaN
2248378,38784019,26864737,False,2019-07-16 19:21:55,2019-06-30 00:01:32,14,True,OTT,0.0000,1,2019-07-14 11:05:41,NaT,NaN
2248379,38965551,24049361,False,2019-07-11 02:07:15,2019-06-30 00:01:32,14,False,OTT,0.0000,0,2019-06-30 00:01:32,NaT,NaN
2248380,34410719,29969407,False,2019-07-07 14:15:50,2019-06-30 00:01:31,14,False,OTT,0.0000,0,2019-06-30 01:05:36,NaT,False
2248383,31072580,25593373,True,NaT,2019-06-30 00:01:28,14,True,OTT,5.2848,2,2020-01-11 10:05:25,NaT,NaN
2248384,39575996,21199804,False,2019-06-30 16:28:31,2019-06-30 00:01:28,14,False,OTT,0.0000,0,2019-06-30 01:05:35,NaT,False
2248386,38865556,27585257,False,NaT,2019-06-30 00:01:25,14,True,OTT,4.9178,1,2019-07-14 14:33:09,NaT,False
2248387,34437033,22486506,False,2019-06-30 16:33:46,2019-06-30 00:01:25,14,False,OTT,0.0000,0,2019-06-30 00:01:25,NaT,False
2248391,30967722,24792193,True,NaT,2019-06-30 00:01:11,14,True,OTT,4.7343,3,2020-03-13 19:27:38,NaT,False
2248392,34428685,22348406,False,2019-07-07 14:01:09,2019-06-30 00:01:08,14,False,OTT,0.0000,0,2019-06-30 00:01:08,NaT,NaN
2248393,30177012,28661481,False,2019-07-09 15:32:06,2019-06-30 00:00:59,14,False,OTT,0.0000,0,2019-06-30 00:00:59,NaT,NaN
2248394,30947283,26986758,False,2019-07-12 23:23:24,2019-06-30 00:00:51,14,False,OTT,0.0000,0,2019-06-30 01:05:29,NaT,False
2248396,39561825,22320767,False,2019-11-27 09:30:04,2019-06-30 00:00:34,14,True,OTT,4.5875,1,2019-07-14 10:43:57,NaT,False
2248397,38865556,23575229,False,2019-06-30 00:51:54,2019-06-30 00:00:19,14,False,OTT,0.0000,0,2019-06-30 00:05:53,NaT,False
2248398,38960743,27633581,False,2019-07-06 13:25:38,2019-06-30 00:00:14,14,False,OTT,0.0000,0,2019-06-30 00:00:14,NaT,NaN
2248399,31803812,21965147,False,2019-07-04 15:37:24,2019-06-30 00:00:13,14,False,OTT,0.0000,0,2019-06-30 00:00:13,NaT,NaN
2248401,33218156,21781165,True,NaT,2019-06-30 00:00:06,14,True,OTT,3.8902,1,2019-07-14 11:05:50,NaT,NaN
2248402,34478389,27625059,False,2019-07-01 10:27:01,2019-06-30 00:00:06,14,False,OTT,0.0000,0,2019-06-30 00:00:06,NaT,NaN
2248405,38647874,27845350,False,NaT,2019-06-30 00:00:04,14,True,OTT,3.5232,2,2019-09-11 11:07:12,NaT,NaN
2248413,30859916,26845271,False,NaT,2019-06-30 06:24:24,0,True,google,0.6239,7,2019-12-25 20:23:27,NaT,NaN

In [7]:
tab = pd.crosstab(df2['trial_completed_TF'], df2['payment_period'], normalize=False)
tab

payment_period,0,1,2,3,4,5,6,7,8,9,10,11,12
trial_completed_TF,,,,,,,,,,,,,
False,660915,12,0,0,0,0,0,0,0,0,0,0,0
True,127042,420858,109827,28950,9939,5938,2390,1416,961,604,504,1,3

In [8]:
df3 = pd.merge(df1, df2)
df3

,subid,package_type,num_weekly_services_utilized,preferred_genre,intended_use,weekly_consumption_hour,num_ideal_streaming_services,retarget_TF,age,male_TF,...,current_sub_TF,cancel_date,num_trial_days,trial_completed_TF,billing_channel,revenue_net_1month,payment_period,last_payment,next_payment,renew
0,26844789,enhanced,3.362885,regional,replace OTT,36.001186,1.951776,False,25.0,True,...,False,2019-12-08 15:05:25,14,False,OTT,0.0000,0,2019-12-07 17:34:29,NaT,False
1,29726122,base,2.049135,comedy,access to exclusive content,20.051667,1.860289,False,61.0,False,...,True,NaT,14,True,OTT,4.5875,1,2020-03-05 13:52:53,NaT,False
2,20299962,base,3.002048,drama,access to exclusive content,34.551230,1.870503,False,23.0,False,...,True,NaT,14,True,OTT,3.4498,1,2020-03-20 13:54:48,NaT,False
3,24930568,base,NaN,comedy,access to exclusive content,25.851492,NaN,False,73.0,False,...,False,2020-02-24 19:20:55,14,False,OTT,0.0000,0,2020-02-23 18:05:22,NaT,False
4,21361112,enhanced,NaN,comedy,access to exclusive content,37.451142,NaN,False,24.0,True,...,False,2019-12-07 11:00:37,14,False,OTT,0.0000,0,2019-12-01 08:05:17,NaT,False
5,25393847,base,2.452687,regional,supplement OTT,28.751405,1.842940,False,57.0,False,...,False,2019-10-06 14:56:52,14,False,OTT,0.0000,0,2019-09-28 22:48:14,NaT,False
6,23163827,economy,2.876856,comedy,replace OTT,33.101274,1.867353,False,54.0,False,...,False,2019-08-29 23:44:11,14,False,OTT,0.0000,0,2019-08-17 06:45:22,NaT,False
7,26874196,base,NaN,comedy,access to exclusive content,NaN,NaN,False,NaN,False,...,True,NaT,14,True,OTT,4.5875,1,2020-03-23 11:05:22,NaT,NaN
8,27648682,enhanced,NaN,comedy,replace OTT,27.301448,NaN,False,26.0,False,...,False,2019-10-02 00:24:26,14,False,OTT,0.0000,0,2019-10-02 05:57:35,NaT,False
9,21760199,NaN,NaN,NaN,expand international access,30.201361,NaN,False,32.0,False,...,False,2019-07-06 02:06:13,14,False,OTT,0.0000,0,2019-07-06 01:59:03,NaT,False
10,21511732,enhanced,2.320133,comedy,replace OTT,27.301448,1.849591,True,26.0,False,...,False,2020-04-12 09:52:49,14,True,OTT,3.2296,1,2019-11-25 13:37:29,NaT,False
11,22090440,base,3.701633,drama,access to exclusive content,22.951579,2.330133,False,65.0,False,...,False,2020-03-11 11:57:47,14,False,OTT,0.0000,0,2020-03-03 19:53:02,NaT,False
12,28863903,base,2.205253,drama,replace OTT,21.501623,1.929349,False,50.0,False,...,False,2020-03-15 21:01:01,14,False,OTT,0.0000,0,2020-03-05 23:02:38,NaT,False
13,29576692,NaN,3.012358,NaN,expand international access,34.551230,1.927293,False,31.0,False,...,False,2019-09-07 18:15:13,14,True,OTT,4.5875,1,2019-07-28 10:29:10,NaT,False
14,23676530,base,NaN,comedy,access to exclusive content,24.401536,NaN,False,21.0,False,...,False,2020-03-09 20:21:29,14,False,OTT,0.0000,0,2020-03-09 23:04:27,NaT,False
15,26520640,enhanced,2.493926,drama,access to exclusive content,24.401536,1.959115,False,37.0,False,...,False,2020-03-26 14:11:46,14,False,OTT,0.0000,0,2020-03-13 14:01:42,NaT,False
16,29773460,base,NaN,comedy,access to exclusive content,NaN,NaN,False,NaN,False,...,True,NaT,14,True,OTT,4.5875,1,2020-04-02 14:28:27,NaT,False
17,20668260,economy,4.217122,drama,access to exclusive content,21.501623,2.623452,False,49.0,False,...,False,2020-03-31 21:55:51,14,True,OTT,0.0000,1,2020-03-31 14:22:21,NaT,False
18,21447938,base,2.788487,drama,replace OTT,30.201361,1.860907,False,59.0,False,...,True,NaT,14,True,OTT,4.5875,1,2020-01-04 13:39:08,NaT,False
19,25575254,economy,NaN,comedy,access to exclusive content,NaN,NaN,False,NaN,False,...,True,NaT,14,True,OTT,4.9912,1,2020-02-23 13:49:40,NaT,False
20,29615706,enhanced,2.626477,regional,access to exclusive content,25.851492,1.952461,False,61.0,False,...,False,2019-11-16 14:30:05,14,False,OTT,0.0000,0,2019-11-09 05:54:33,NaT,False
21,26461912,enhanced,4.314329,comedy,supplement OTT,25.851492,2.372655,False,20.0,False,...,True,NaT,14,True,OTT,4.8811,1,2020-03-11 13:59:39,NaT,NaN
22,24342004,base,NaN,comedy,access to exclusive content,NaN,NaN,False,NaN,False,...,False,NaT,14,True,OTT,0.0000,0,2019-12-01 04:39:46,NaT,False
23,27436215,base,2.655933,drama,access to exclusive content,27.301448,1.867558,False,53.0,False,...,False,2019-10-21 14:05:34,14,False,OTT,0.0000,0,2019-10-08 13:34:22,NaT,False
24,22401037,base,3.119873,comedy,access to exclusive content,25.851492,1.844277,False,53.0,False,...,False,2020-03-29 11:44:36,14,True,OTT,0.0000,0,2020-02-27 19:47:16,NaT,False
25,29909729,enhanced,NaN,comedy,access to exclusive content,27.301448,NaN,False,39.0,False,...,False,2019-11-26 21:11:49,14,False,OTT,0.0000,0,2019-11-26 21:05:21,NaT,False
26,26663165,NaN,2.471316,NaN,education,33.101274,1.883824,False,41.0,False,...,False,2019-07-23 15:09:54,14,False,OTT,0.0000,0,2019-07-13 00:31:32,NaT,False
27,20458759,enhanced,NaN,comedy,replace OTT,25.851492,NaN,False,55.0,False,...,False,2020-03-10 16:07:09,14,False,OTT,0.0000,0,2020-03-04 19:05:25,NaT,False
28,27936781,base,NaN,comedy,access to exclusive content,38.901099,NaN,False,43.0,True,...,False,2020-02-25 21:37:40,14,False,OTT,0.0000,0,2020-02-20 19:43:06,NaT,False
29,20395793,base,2.264166,drama,access to exclusive content,20.051667,1.890122,False,25.0,False,...,False,2020-04-04 14:49:16,14,False,OTT,0.0000,0,2020-03-22 01:05:21,NaT,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135020,24382135,base,NaN,comedy,replace OTT,NaN,NaN,False,NaN,False,...,True,NaT,14,True,OTT,4.5875,1,2020-03-11 13:59:39,NaT,False
135021,20426508,base,2.405557,comedy,supplement OTT,20.051667,1.887379,False,38.0,False,...,False,2019-10-27 02:26:19,14,False,OTT,0.0000,0,2019-10-18 15:51:52,NaT,False
135022,29333010,base,NaN,drama,access to exclusive content,22.951579,NaN,False,71.0,False,...,False,2020-03-01 18:43:40,14,False,OTT,0.0000,0,2020-02-29 12:02:07,NaT,False
135023,23142589,base,2.228819,comedy,access to exclusive content,24.401536,1.822255,False,57.0,False,...,False,2019-12-30 07:16:52,14,True,OTT,4.5875,1,2019-12-11 11:05:19,NaT,False
135024,23189569,NaN,2.520437,NaN,expand international access,28.751405,1.938197,False,28.0,False,...,False,NaT,14,True,OTT,0.9175,2,2019-11-20 13:39:31,NaT,False
135025,25749000,economy,2.926934,drama,supplement OTT,30.201361,1.856862,False,67.0,False,...,True,NaT,14,True,OTT,3.6700,2,2020-03-31 11:05:26,NaT,False
135026,24139708,base,NaN,drama,access to exclusive content,34.551230,NaN,False,38.0,True,...,False,2020-03-23 17:07:33,14,False,OTT,0.0000,0,2020-03-16 13:05:22,NaT,False
135027,29324294,base,NaN,other,replace OTT,28.751405,NaN,False,59.0,False,...,False,2019-11-25 16:41:43,14,False,OTT,0.0000,0,2019-11-16 17:49:41,NaT,False
135028,22757321,enhanced,2.555784,comedy,replace OTT,28.751405,1.921189,False,26.0,False,...,False,2019-11-16 03:51:56,14,False,OTT,0.0000,0,2019-11-04 15:05:50,NaT,False
135029,23516585,NaN,3.937287,NaN,expand international access,25.851492,1.944715,False,46.0,False,...,True,NaT,14,True,OTT,3.4498,3,2020-04-13 14:18:37,NaT,False
135030,25097872,enhanced,NaN,comedy,replace OTT,30.201361,NaN,False,50.0,False,...,False,2020-02-23 06:28:00,14,False,OTT,0.0000,0,2020-02-23 07:42:01,NaT,False
135031,21934088,base,2.685618,international,replace OTT,28.751405,1.880690,False,30.0,False,...,True,NaT,14,True,OTT,4.5875,1,2020-04-07 14:26:08,NaT,False
135032,28985855,NaN,4.172934,NaN,expand international access,27.301448,2.603905,False,25.0,False,...,False,2019-12-01 09:55:36,14,True,OTT,4.5875,1,2019-07-18 10:32:06,NaT,False
135033,28111970,enhanced,2.420285,comedy,access to exclusive content,28.751405,1.828606,True,55.0,False,...,False,2019-10-09 02:25:35,14,False,OTT,0.0000,0,2019-10-08 05:55:09,NaT,False
135034,27161457,base,NaN,drama,access to exclusive content,NaN,NaN,False,NaN,False,...,True,NaT,14,True,OTT,4.5875,2,2020-03-26 11:05:26,NaT,NaN
135035,29909208,NaN,2.324552,NaN,expand international access,25.851492,1.884191,False,19.0,False,...,False,NaT,14,True,OTT,4.9912,2,2019-12-03 13:36:03,NaT,False
135036,24315621,base,NaN,comedy,replace OTT,NaN,NaN,False,NaN,False,...,False,NaT,14,True,OTT,4.5875,1,2019-12-04 13:39:46,NaT,False
135037,25927672,NaN,2.935771,NaN,expand regional access,30.201361,1.958703,False,34.0,False,...,False,NaT,14,True,OTT,4.5875,1,2019-08-09 14:32:54,NaT,False
135038,29190645,enhanced,2.764924,comedy,access to exclusive content,25.851492,1.981060,False,46.0,False,...,True,NaT,14,True,OTT,4.5875,1,2020-03-17 13:41:59,NaT,False
135039,26263998,NaN,NaN,NaN,expand international access,-8.947459,NaN,False,43.0,False,...,False,2019-07-26 21:13:26,14,True,OTT,0.0000,1,2019-07-26 10:06:31,NaT,NaN
135040,24317364,enhanced,2.479196,comedy,replace OTT,30.201361,1.854666,False,52.0,False,...,False,2019-08-26 00:42:34,14,False,OTT,0.0000,0,2019-08-23 14:05:47,NaT,False
135041,26828621,base,3.672180,drama,access to exclusive content,27.301448,2.317104,False,44.0,False,...,True,NaT,14,True,OTT,-0.6973,1,2020-03-11 13:59:39,NaT,NaN
135042,28920930,enhanced,NaN,regional,replace OTT,NaN,NaN,False,NaN,False,...,True,NaT,14,True,OTT,4.9178,2,2020-01-29 13:51:38,NaT,False
135043,22218943,economy,NaN,comedy,replace OTT,37.451142,NaN,False,67.0,True,...,False,2019-11-19 01:56:54,14,False,OTT,0.0000,0,2019-11-16 06:10:01,NaT,False
135044,25492551,base,2.514545,comedy,access to exclusive content,30.201361,1.968236,False,32.0,False,...,False,2019-10-01 20:19:02,14,False,OTT,0.0000,0,2019-09-30 22:07:37,NaT,False
135045,21928274,base,NaN,drama,replace OTT,NaN,NaN,False,NaN,False,...,True,NaT,14,True,OTT,4.5875,1,2020-01-28 13:52:00,NaT,False
135046,25549852,enhanced,NaN,comedy,access to exclusive content,28.751405,NaN,False,61.0,False,...,False,2020-03-06 04:07:06,14,False,OTT,0.0000,0,2020-03-06 06:37:50,NaT,False
135047,25835684,base,2.169904,drama,access to exclusive content,24.401536,1.881068,False,43.0,False,...,False,2020-01-12 13:42:46,14,False,OTT,0.0000,0,2020-01-01 22:43:56,NaT,False
135048,21434712,enhanced,2.594078,comedy,supplement OTT,28.751405,1.905485,False,38.0,False,...,False,2019-11-25 22:25:46,14,False,OTT,0.0000,0,2019-11-17 15:05:20,NaT,False
135049,25843074,enhanced,2.361370,comedy,replace OTT,27.301448,1.835189,True,49.0,False,...,False,NaT,14,True,OTT,4.5875,1,2019-12-21 10:05:18,NaT,False

In [9]:
df3.shape

(135050, 40)

# AB Testing

In [10]:
def cv_TF(row):
    if row.trial_completed_TF==False:
        return False
    elif (row.payment_period==True) and (row.payment_period==0):
        return False
    else:
        return True

In [11]:
df3.loc[:,'cv_TF'] = df3.apply(cv_TF,axis=1)

In [12]:
df3['cv_TF'].value_counts()

False    72666
True     62384
Name: cv_TF, dtype: int64

In [13]:
ab_df=df3[['plan_type','cv_TF']]
ab_df.head()
ab_df['plan_type'].value_counts()

base_uae_14_day_trial                134750
high_uae_14_day_trial                   242
low_uae_no_trial                         33
base_eur_14_day_trial                    10
high_sar_14_day_trial                    10
high_aud_14_day_trial                     2
base_uae_no_trial_7_day_guarantee         1
low_gbp_14_day_trial                      1
high_jpy_14_day_trial                     1
Name: plan_type, dtype: int64

In [14]:
ab_df=ab_df.loc[ab_df.plan_type.isin(['base_uae_14_day_trial','low_uae_no_trial','high_uae_14_day_trial'])]
ab_df.head()

               plan_type  cv_TF
0  base_uae_14_day_trial  False
1  base_uae_14_day_trial   True
2  base_uae_14_day_trial   True
3  base_uae_14_day_trial  False
4  base_uae_14_day_trial  False

In [15]:
ab_table = ab_df.pivot_table(values='cv_TF', index='plan_type', aggfunc=np.sum)
# add additional columns to the pivot table
ab_table['total'] = ab_df.pivot_table(values='cv_TF', index='plan_type', aggfunc=lambda x: len(x))
ab_table['rate'] = ab_df.pivot_table(values='cv_TF', index='plan_type')
ab_table.head()

                         cv_TF   total      rate
plan_type
base_uae_14_day_trial  62236.0  134750  0.461863
high_uae_14_day_trial    105.0     242  0.433884
low_uae_no_trial          27.0      33  0.818182

In [16]:
#treatment:high_uae_14_day_trial
#Control:base_uae_14_day_trial
A_converted = ab_table ['cv_TF'][0]
N_A = ab_table ['total'][0]
p_A = ab_table ['rate'][0]
B_converted = ab_table ['cv_TF'][1]
N_B = ab_table ['total'][1]
p_B = ab_table ['rate'][1]

In [17]:
pooled_prob = (p_A*N_A+p_B*N_B)/(N_A + N_B)
z=(p_B - p_A)/(pooled_prob*(1-pooled_prob)*(1/N_A +1/N_B))**0.5
z

-0.8722509558870999

In [18]:
#treatment:low_uae_no_trial
#Control:base_uae_14_day_trial
B_converted = ab_table ['cv_TF'][2]
N_B = ab_table ['total'][2]
p_B = ab_table ['rate'][2]

In [19]:
pooled_prob = (p_A*N_A+p_B*N_B)/(N_A + N_B)
z=(p_B - p_A)/(pooled_prob*(1-pooled_prob)*(1/N_A +1/N_B))**0.5
z

4.105198027843201

# Allocation

In [20]:
spending_data = pd.read_excel('advertising_spend_data.xlsx')
spending_data.columns=['year','month','attribution_technical','spend']
spending_data.head()

   year  month    attribution_technical  spend
0  2019      6                 facebook  84800
1  2019      6                    email  75000
2  2019      6                   search  17300
3  2019      6  brand sem intent google  21400
4  2019      6                affiliate  11900

In [21]:
len(df3['subid'].unique())

135050

In [22]:
len(df2['subid'].unique())

1369360

In [23]:
#Since many data of users in df3 is absent from df2, we need to calculated the proportion, and use it as multiplier.
df2['month']= df2['account_creation_date'].dt.month
df2['year']= df2['account_creation_date'].dt.year

In [24]:
df2_nondu = df2.drop_duplicates(subset=['subid'])
df2_count = pd.DataFrame(df2_nondu.groupby(['year','month'])['account_creation_date'].count())
df2_count.reset_index(inplace=True)

In [25]:
df3['month']=df3['account_creation_date'].dt.month
df3['year'] = df3['account_creation_date'].dt.year

In [26]:
s_count = pd.DataFrame(df3.groupby(['year','month'])['account_creation_date'].count())

s_count.reset_index(inplace=True)
s_count.head()

   year  month  account_creation_date
0  2019      6                   2135
1  2019      7                  20924
2  2019      8                  11851
3  2019      9                  11931
4  2019     10                  10334

In [27]:
table1 = df2_count.merge(s_count,on=['year','month'])

table1['multiplier'] = table1['account_creation_date_x'] / table1['account_creation_date_y']

In [28]:
table1

   year  month  account_creation_date_x  account_creation_date_y  multiplier
0  2019      6                    20849                     2135    9.765340
1  2019      7                   221007                    20924   10.562369
2  2019      8                   108490                    11851    9.154502
3  2019      9                   109504                    11931    9.178107
4  2019     10                   116091                    10334   11.233888
5  2019     11                   194123                    18766   10.344399
6  2019     12                   134212                    13163   10.196156
7  2020      1                    96536                     8976   10.754902
8  2020      2                   176830                    17831    9.916998
9  2020      3                   191718                    19139   10.017138

In [29]:
df1['attribution_technical'].value_counts()

facebook                   80251
email                      25690
search                     25306
organic                    22013
brand sem intent google    18524
google_organic             10691
affiliate                   9894
email_blast                 7277
pinterest                   6065
referral                    5170
facebook_organic            3272
discovery                   2571
brand sem intent bing       2231
other                       1786
display                     1407
bing                        1146
internal                    1122
podcast                      985
youtube                      913
bing_organic                 369
vod                          297
ott                          158
direct_mail                  139
quora                        100
samsung                       86
appstore                      44
criteo                        44
pinterest_organic             30
influencer                    21
playstore                     12
content_greatist               5
twitter                        5
tv                             4
Name: attribution_technical, dtype: int64

In [30]:
df1['attribution_survey'].value_counts()
# Since channels listed in "attribution_survey" do not conclude some channels in advertising spend data, we choose "attribution_survey"

facebook            119126
tv                   39904
referral             20882
search                8492
pinterest             7856
other                 6496
public_radio          6219
social_organic        3869
youtube               3108
podcast               2995
affiliate             1962
ott                   1443
sirius xm             1122
facebook_organic       765
direct_mail            408
amfm_radio             337
Name: attribution_survey, dtype: int64

In [31]:
valued_users=df3.loc[(df3['cv_TF']==True)&(df3.attribution_technical.isin(['facebook','email','search','brand sem intent google','affiliate','email_blast','pinterest','referral']))]
valued_users

,subid,package_type,num_weekly_services_utilized,preferred_genre,intended_use,weekly_consumption_hour,num_ideal_streaming_services,retarget_TF,age,male_TF,...,trial_completed_TF,billing_channel,revenue_net_1month,payment_period,last_payment,next_payment,renew,cv_TF,month,year
2,20299962,base,3.002048,drama,access to exclusive content,34.551230,1.870503,False,23.0,False,...,True,OTT,3.4498,1,2020-03-20 13:54:48,NaT,False,True,3,2020
7,26874196,base,NaN,comedy,access to exclusive content,NaN,NaN,False,NaN,False,...,True,OTT,4.5875,1,2020-03-23 11:05:22,NaT,NaN,True,3,2020
13,29576692,NaN,3.012358,NaN,expand international access,34.551230,1.927293,False,31.0,False,...,True,OTT,4.5875,1,2019-07-28 10:29:10,NaT,False,True,7,2019
17,20668260,economy,4.217122,drama,access to exclusive content,21.501623,2.623452,False,49.0,False,...,True,OTT,0.0000,1,2020-03-31 14:22:21,NaT,False,True,3,2020
19,25575254,economy,NaN,comedy,access to exclusive content,NaN,NaN,False,NaN,False,...,True,OTT,4.9912,1,2020-02-23 13:49:40,NaT,False,True,2,2020
21,26461912,enhanced,4.314329,comedy,supplement OTT,25.851492,2.372655,False,20.0,False,...,True,OTT,4.8811,1,2020-03-11 13:59:39,NaT,NaN,True,2,2020
22,24342004,base,NaN,comedy,access to exclusive content,NaN,NaN,False,NaN,False,...,True,OTT,0.0000,0,2019-12-01 04:39:46,NaT,False,True,12,2019
24,22401037,base,3.119873,comedy,access to exclusive content,25.851492,1.844277,False,53.0,False,...,True,OTT,0.0000,0,2020-02-27 19:47:16,NaT,False,True,2,2020
33,21639671,base,NaN,comedy,access to exclusive content,NaN,NaN,True,NaN,False,...,True,OTT,4.5875,1,2019-12-15 10:05:18,NaT,False,True,11,2019
36,27955482,enhanced,NaN,comedy,supplement OTT,NaN,NaN,False,NaN,False,...,True,OTT,5.0646,1,2019-10-13 13:33:52,NaT,False,True,9,2019
39,28506369,enhanced,2.850348,regional,replace OTT,30.201361,1.855627,False,46.0,True,...,True,OTT,5.0279,1,2019-12-23 13:38:38,NaT,False,True,12,2019
43,26156384,NaN,2.411448,NaN,expand international access,21.501623,1.857341,False,51.0,False,...,True,OTT,4.5875,3,2020-03-18 14:33:41,NaT,False,True,7,2019
44,26204108,economy,NaN,comedy,access to exclusive content,NaN,NaN,False,NaN,False,...,True,OTT,4.5875,2,2020-01-17 13:41:58,NaT,False,True,9,2019
47,20733152,economy,2.741359,comedy,access to exclusive content,28.751405,1.970636,False,51.0,False,...,True,OTT,4.5875,1,2020-03-06 11:05:24,NaT,False,True,2,2020
49,27918984,base,NaN,comedy,access to exclusive content,14.251842,NaN,False,61.0,False,...,True,OTT,0.0000,1,2020-03-16 14:02:21,NaT,False,True,3,2020
55,25644417,NaN,2.367263,NaN,expand regional access,25.851492,1.870439,False,48.0,False,...,True,OTT,4.5875,1,2019-07-16 11:05:48,NaT,False,True,7,2019
56,25027288,base,2.658881,drama,access to exclusive content,21.501623,1.901508,False,57.0,False,...,True,OTT,4.9178,2,2020-02-26 14:00:49,NaT,False,True,10,2019
61,29998133,NaN,4.290759,NaN,expand regional access,28.751405,2.296941,False,39.0,False,...,True,OTT,3.6700,3,2020-04-02 14:28:27,NaT,False,True,7,2019
62,26716687,NaN,4.108134,NaN,expand regional access,27.301448,2.314088,False,44.0,False,...,True,OTT,1.0276,1,2019-07-25 14:33:47,NaT,False,True,7,2019
64,28078576,NaN,2.720740,NaN,education,30.201361,1.896226,True,42.0,False,...,True,OTT,0.9175,3,2020-03-26 10:05:29,NaT,NaN,True,7,2019
65,20008677,enhanced,NaN,comedy,replace OTT,25.851492,NaN,False,45.0,False,...,True,OTT,0.0000,0,2019-11-28 22:42:26,NaT,False,True,11,2019
74,25806271,NaN,3.009412,NaN,expand regional access,24.401536,1.795414,False,58.0,False,...,True,OTT,4.5875,2,2019-12-19 10:05:19,NaT,False,True,8,2019
76,24821451,enhanced,NaN,other,access to exclusive content,36.001186,NaN,True,60.0,True,...,True,OTT,4.8811,1,2020-02-29 11:05:22,NaT,NaN,True,2,2020
79,28248814,enhanced,NaN,comedy,access to exclusive content,33.101274,NaN,False,56.0,False,...,True,OTT,0.0000,0,2020-01-04 13:39:08,NaT,False,True,1,2020
85,22403115,base,NaN,comedy,supplement OTT,NaN,NaN,False,NaN,False,...,True,OTT,0.0000,1,2019-10-22 10:06:20,NaT,False,True,10,2019
86,23193693,base,NaN,comedy,replace OTT,NaN,NaN,False,NaN,False,...,True,OTT,3.7434,1,2020-03-09 13:58:55,NaT,False,True,2,2020
87,21929654,enhanced,2.700118,comedy,replace OTT,36.001186,1.854460,False,41.0,False,...,True,OTT,4.7343,1,2019-09-03 18:58:06,NaT,False,True,8,2019
89,23590688,base,NaN,comedy,replace OTT,NaN,NaN,False,NaN,False,...,True,OTT,4.5875,1,2020-01-21 11:05:25,NaT,False,True,1,2020
91,24158250,base,3.952012,drama,replace OTT,28.751405,2.310314,False,40.0,False,...,True,OTT,0.0000,0,2020-03-10 06:51:48,NaT,False,True,3,2020
93,28620623,base,NaN,drama,access to exclusive content,NaN,NaN,False,NaN,False,...,True,OTT,3.4498,1,2019-09-25 13:36:21,NaT,False,True,9,2019
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
134961,23227765,base,NaN,comedy,access to exclusive content,NaN,NaN,True,NaN,False,...,True,OTT,3.6700,1,2019-09-18 13:50:20,NaT,False,True,9,2019
134964,21358316,base,2.477725,comedy,replace OTT,27.301448,1.854015,False,24.0,False,...,True,OTT,0.0000,1,2019-10-30 13:53:44,NaT,False,True,10,2019
134970,22558652,base,NaN,comedy,replace OTT,NaN,NaN,False,NaN,False,...,True,OTT,4.5875,1,2020-02-22 13:52:41,NaT,False,True,2,2020
134971,25306093,base,2.361372,international,access to exclusive content,27.301448,1.867833,False,55.0,False,...,True,OTT,3.9269,2,2020-02-19 10:05:24,NaT,False,True,10,2019
134974,29000970,enhanced,2.582295,regional,replace OTT,27.301448,1.867629,False,49.0,False,...,True,OTT,0.0000,0,2019-10-11 05:59:44,NaT,False,True,10,2019
134976,26603666,base,NaN,comedy,access to exclusive content,NaN,NaN,False,NaN,True,...,True,OTT,5.1747,1,2020-02-24 18:59:52,NaT,False,True,2,2020
134977,27830586,economy,5.256931,international,access to exclusive content,40.351055,2.528470,False,62.0,True,...,True,OTT,4.5875,1,2020-04-03 14:00:18,NaT,False,True,3,2020
134979,21158019,NaN,NaN,NaN,expand regional access,25.851492,NaN,False,58.0,False,...,True,OTT,4.8444,2,2019-11-12 11:05:19,NaT,NaN,True,6,2019
134983,27191430,NaN,2.876858,NaN,expand regional access,27.301448,1.965287,False,52.0,False,...,True,OTT,4.5875,1,2019-07-16 14:33:14,NaT,False,True,7,2019
134994,22521900,economy,NaN,drama,access to exclusive content,30.201361,NaN,False,60.0,False,...,True,OTT,4.5875,1,2020-02-22 13:52:41,NaT,False,True,2,2020
134995,29497728,economy,NaN,drama,replace OTT,NaN,NaN,False,NaN,False,...,True,OTT,4.5875,1,2020-01-04 13:51:34,NaT,False,True,12,2019
134996,24521753,enhanced,2.199361,regional,replace OTT,27.301448,1.828811,False,50.0,False,...,True,OTT,0.0000,0,2019-08-22 14:05:41,NaT,False,True,8,2019
134997,20588003,base,2.538110,drama,access to exclusive content,25.851492,1.684862,False,60.0,False,...,True,OTT,3.2296,2,2020-04-08 15:52:52,NaT,False,True,11,2019
134998,27914665,base,NaN,comedy,access to exclusive content,NaN,NaN,False,NaN,False,...,True,OTT,4.5875,1,2020-01-02 10:05:20,NaT,False,True,12,2019
135000,25341091,enhanced,2.435013,drama,replace OTT,24.401536,1.835121,False,59.0,False,...,True,OTT,4.5875,2,2020-04-11 14:22:46,NaT,False,True,11,2019
135002,25113375,economy,NaN,comedy,supplement OTT,NaN,NaN,False,NaN,False,...,True,OTT,4.5875,1,2019-12-13 13:34:14,NaT,False,True,11,2019
135004,24129353,base,NaN,comedy,supplement OTT,NaN,NaN,True,NaN,False,...,True,OTT,4.5875,1,2019-09-15 13:46:48,NaT,False,True,8,2019
135005,27817975,enhanced,NaN,comedy,access to exclusive content,NaN,NaN,False,NaN,True,...,True,OTT,4.5875,1,2020-01-05 10:05:20,NaT,False,True,12,2019
135015,29072415,base,5.793032,drama,access to exclusive content,31.651317,2.602399,False,46.0,False,...,True,OTT,3.2296,1,2019-10-26 13:34:25,NaT,False,True,10,2019
135017,25424389,NaN,2.597023,NaN,expand international access,24.401536,1.939432,False,36.0,False,...,True,OTT,2.5323,2,2019-11-19 13:37:46,NaT,False,True,7,2019
135020,24382135,base,NaN,comedy,replace OTT,NaN,NaN,False,NaN,False,...,True,OTT,4.5875,1,2020-03-11 13:59:39,NaT,False,True,2,2020
135023,23142589,base,2.228819,comedy,access to exclusive content,24.401536,1.822255,False,57.0,False,...,True,OTT,4.5875,1,2019-12-11 11:05:19,NaT,False,True,11,2019
135025,25749000,economy,2.926934,drama,supplement OTT,30.201361,1.856862,False,67.0,False,...,True,OTT,3.6700,2,2020-03-31 11:05:26,NaT,False,True,11,2019
135034,27161457,base,NaN,drama,access to exclusive content,NaN,NaN,False,NaN,False,...,True,OTT,4.5875,2,2020-03-26 11:05:26,NaT,NaN,True,11,2019
135036,24315621,base,NaN,comedy,replace OTT,NaN,NaN,False,NaN,False,...,True,OTT,4.5875,1,2019-12-04 13:39:46,NaT,False,True,11,2019
135038,29190645,enhanced,2.764924,comedy,access to exclusive content,25.851492,1.981060,False,46.0,False,...,True,OTT,4.5875,1,2020-03-17 13:41:59,NaT,False,True,3,2020
135039,26263998,NaN,NaN,NaN,expand international access,-8.947459,NaN,False,43.0,False,...,True,OTT,0.0000,1,2019-07-26 10:06:31,NaT,NaN,True,7,2019
135041,26828621,base,3.672180,drama,access to exclusive content,27.301448,2.317104,False,44.0,False,...,True,OTT,-0.6973,1,2020-03-11 13:59:39,NaT,NaN,True,2,2020
135042,28920930,enhanced,NaN,regional,replace OTT,NaN,NaN,False,NaN,False,...,True,OTT,4.9178,2,2020-01-29 13:51:38,NaT,False,True,9,2019
135045,21928274,base,NaN,drama,replace OTT,NaN,NaN,False,NaN,False,...,True,OTT,4.5875,1,2020-01-28 13:52:00,NaT,False,True,1,2020

In [32]:
ad_table=valued_users.groupby(['year','month','attribution_technical'])
counts=ad_table['subid'].count()
ad_df=pd.DataFrame(counts)
ad_df.reset_index(inplace=True)
ad_df.head()

   year  month    attribution_technical  subid
0  2019      6                affiliate     41
1  2019      6  brand sem intent google     90
2  2019      6                    email    137
3  2019      6              email_blast     58
4  2019      6                 facebook    491

In [33]:
mtp_users=pd.merge(ad_df,table1[['year','month','multiplier']], left_on=['year','month'],right_on=['year','month'],how='right')
mtp_users.head()

   year  month    attribution_technical  subid  multiplier
0  2019      6                affiliate     41     9.76534
1  2019      6  brand sem intent google     90     9.76534
2  2019      6                    email    137     9.76534
3  2019      6              email_blast     58     9.76534
4  2019      6                 facebook    491     9.76534

In [34]:
mtp_users['num_users']=mtp_users['subid'] * mtp_users['multiplier']
mtp_users=mtp_users.drop(columns=['subid','multiplier'])
mtp_users

    year  month    attribution_technical     num_users
0   2019      6                affiliate    400.378923
1   2019      6  brand sem intent google    878.880562
2   2019      6                    email   1337.851522
3   2019      6              email_blast    566.389696
4   2019      6                 facebook   4794.781733
5   2019      6                pinterest    126.949415
6   2019      6                 referral    136.714754
7   2019      6                   search    292.960187
8   2019      7                affiliate   3622.892420
9   2019      7  brand sem intent google   8228.085118
10  2019      7                    email  15019.688109
11  2019      7              email_blast   7964.025903
12  2019      7                 facebook  35764.179985
13  2019      7                pinterest   2450.469509
14  2019      7                 referral   2756.778197
15  2019      7                   search   4753.065857
16  2019      8                affiliate   2288.625432
17  2019      8  brand sem intent google   4394.160830
18  2019      8                    email   7360.219391
19  2019      8              email_blast   1977.372374
20  2019      8                 facebook  18373.084972
21  2019      8                pinterest   1144.312716
22  2019      8                 referral   1519.647287
23  2019      8                   search   3954.744747
24  2019      9                affiliate   2331.239293
25  2019      9  brand sem intent google   4249.463750
26  2019      9                    email   6002.482273
27  2019      9              email_blast   5415.083396
28  2019      9                 facebook  13629.489565
29  2019      9                pinterest   1138.085324
..   ...    ...                      ...           ...
50  2019     12                    email   7504.370736
51  2019     12              email_blast    907.457874
52  2019     12                 facebook  21044.865760
53  2019     12                pinterest   1733.346502
54  2019     12                 referral   2508.254349
55  2019     12                   search   8676.928664
56  2020      1                affiliate   1494.931373
57  2020      1  brand sem intent google   5183.862745
58  2020      1                    email   4839.705882
59  2020      1              email_blast    139.813725
60  2020      1                 facebook   9786.960784
61  2020      1                pinterest   1451.911765
62  2020      1                 referral   1914.372549
63  2020      1                   search   6807.852941
64  2020      2                affiliate   3034.601537
65  2020      2  brand sem intent google   7090.653917
66  2020      2                    email   8568.286692
67  2020      2              email_blast    257.841961
68  2020      2                 facebook  22134.740620
69  2020      2                pinterest   1904.063709
70  2020      2                 referral   2568.502608
71  2020      2                   search  12158.240144
72  2020      3                affiliate   4147.095042
73  2020      3  brand sem intent google   6050.351220
74  2020      3                    email  11259.262866
75  2020      3              email_blast    210.359893
76  2020      3                 facebook  23349.948169
77  2020      3                pinterest   1632.793458
78  2020      3                 referral   2884.935681
79  2020      3                   search  10407.806155

[80 rows x 4 columns]

In [35]:
ad_m=pd.merge(mtp_users,spending_data, left_on=['year','month','attribution_technical'],right_on=['year','month','attribution_technical'],how='right')
ad_m.head()

   year  month    attribution_technical    num_users  spend
0  2019      6                affiliate   400.378923  11900
1  2019      6  brand sem intent google   878.880562  21400
2  2019      6                    email  1337.851522  75000
3  2019      6              email_blast   566.389696  10500
4  2019      6                 facebook  4794.781733  84800

In [232]:
ad_m['CAC']=ad_m['spend']/ad_m['num_users']
ad_m.head()
ad_m.to_csv('avg_CAC.csv')

In [37]:
marg_table=pd.pivot_table(ad_m,index=['attribution_technical','year','month'],values=['num_users','spend'],aggfunc=np.sum)
marg_table.reset_index(inplace=True)
marg_table.head()

  attribution_technical  year  month    num_users  spend
0             affiliate  2019      6   400.378923  11900
1             affiliate  2019      7  3622.892420  12000
2             affiliate  2019      8  2288.625432  16300
3             affiliate  2019      9  2331.239293  16400
4             affiliate  2019     10   820.073834  12200

In [38]:
marg_table['marginal_spend']=marg_table['spend'].shift(0)-marg_table['spend'].shift(1)
marg_table['marginal_conv']=marg_table['num_users'].shift(0)-marg_table['num_users'].shift(1)
marg_table.head()

,attribution_technical,year,month,num_users,spend,marginal_spend,marginal_conv
0,affiliate,2019,6,400.378923,11900,NaN,NaN
1,affiliate,2019,7,3622.892420,12000,100.0,3222.513497
2,affiliate,2019,8,2288.625432,16300,4300.0,-1334.266988
3,affiliate,2019,9,2331.239293,16400,100.0,42.613860
4,affiliate,2019,10,820.073834,12200,-4200.0,-1511.165459

In [39]:
for i in [0,10,20,30,40,50,60,70]:
    marg_table['marginal_spend'][i]= marg_table['spend'][i]
    marg_table['marginal_conv'][i]= marg_table['num_users'][i]

/Users/huyi/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

/Users/huyi/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [40]:
marg_table.head()

,attribution_technical,year,month,num_users,spend,marginal_spend,marginal_conv
0,affiliate,2019,6,400.378923,11900,11900.0,400.378923
1,affiliate,2019,7,3622.892420,12000,100.0,3222.513497
2,affiliate,2019,8,2288.625432,16300,4300.0,-1334.266988
3,affiliate,2019,9,2331.239293,16400,100.0,42.613860
4,affiliate,2019,10,820.073834,12200,-4200.0,-1511.165459

In [233]:
marg_table['marginal_CAC']=marg_table['marginal_spend']/marg_table['marginal_conv']
marg_table.head()
marg_table.to_csv('mgn_CAC.csv')

# Churn Modeling

1. data preprocessing

In [107]:
#For the dataset "Engagement", calculate the daily data for each column.
Egm_data=pd.read_pickle("engagement.dms")
Egm_data.head()

,subid,date,app_opens,cust_service_mssgs,num_videos_completed,num_videos_more_than_30_seconds,num_videos_rated,num_series_started,payment_period
1,22349235,2019-07-01,1.0,1.0,0.0,6.0,0.0,0.0,0.0
2,22349235,2019-07-02,1.0,0.0,0.0,5.0,0.0,0.0,0.0
3,22349235,2019-07-03,0.0,1.0,0.0,0.0,0.0,0.0,0.0
50,20848497,2019-07-02,1.0,0.0,7.0,7.0,0.0,0.0,0.0
51,22680106,2019-07-02,2.0,1.0,7.0,7.0,0.0,1.0,0.0

In [108]:
df2['current_sub_TF'].value_counts()

False    1040049
True      329311
Name: current_sub_TF, dtype: int64

In [109]:
Egm_data = Egm_data.groupby('subid').agg({'date': ['min', 'max'], 'app_opens':  'sum',
                                           'cust_service_mssgs' : 'sum', 'num_videos_rated': 'sum',
                                           'num_videos_completed': 'sum', 'num_videos_more_than_30_seconds': 'sum',
                                           'num_series_started': 'sum','payment_period':'max'}).reset_index()
Egm_data.columns = ['subid','day_min', 'day_max',  
                     'app_opens', 'cust_service_mssgs', 'num_videos_rated', 'num_videos_completed',
                    'num_videos_more_than_30_seconds', 'num_series_started','payment_period_max']
Egm_data['days']=(Egm_data['day_max']-Egm_data['day_min']).dt.days+1
Egm_data

,subid,day_min,day_max,app_opens,cust_service_mssgs,num_videos_rated,num_videos_completed,num_videos_more_than_30_seconds,num_series_started,payment_period_max,days
0,20000062,2019-06-30,2019-07-04,4.0,3.0,0.0,6.0,23.0,1.0,0.0,5
1,20000405,2020-03-08,2020-03-18,5.0,4.0,0.0,13.0,17.0,1.0,0.0,11
2,20000604,2020-02-09,2020-03-05,14.0,5.0,0.0,8.0,68.0,1.0,1.0,26
3,20000685,2020-03-03,2020-04-15,46.0,10.0,0.0,14.0,165.0,8.0,1.0,44
4,20000741,2019-08-25,2019-08-26,1.0,1.0,0.0,2.0,7.0,0.0,0.0,2
5,20000796,2019-09-26,2019-11-10,222.0,38.0,3.0,194.0,203.0,42.0,1.0,46
6,20000809,2019-07-13,2019-10-14,7.0,2.0,0.0,2.0,11.0,1.0,3.0,94
7,20000863,2020-01-08,2020-01-20,9.0,5.0,0.0,6.0,34.0,0.0,0.0,13
8,20000963,2019-07-12,2019-07-23,8.0,3.0,0.0,32.0,42.0,4.0,0.0,12
9,20000992,2020-02-15,2020-02-18,4.0,2.0,0.0,11.0,21.0,3.0,0.0,4
10,20001112,2019-09-14,2019-10-28,24.0,3.0,0.0,45.0,149.0,26.0,1.0,45
11,20001132,2020-02-21,2020-04-06,45.0,17.0,6.0,144.0,206.0,18.0,1.0,46
12,20001164,2020-03-04,2020-03-12,56.0,4.0,0.0,40.0,51.0,8.0,0.0,9
13,20001169,2019-10-05,2019-10-07,6.0,5.0,0.0,12.0,18.0,1.0,0.0,3
14,20001209,2019-11-27,2019-12-05,3.0,1.0,0.0,2.0,22.0,0.0,0.0,9
15,20001231,2019-10-29,2019-11-12,9.0,1.0,0.0,4.0,13.0,0.0,0.0,15
16,20001350,2020-01-26,2020-02-04,5.0,2.0,0.0,2.0,16.0,0.0,0.0,10
17,20001429,2019-12-01,2019-12-15,15.0,21.0,0.0,74.0,74.0,15.0,0.0,15
18,20001679,2019-11-30,2019-12-11,5.0,3.0,0.0,8.0,17.0,0.0,0.0,12
19,20001699,2019-07-05,2019-07-09,5.0,2.0,0.0,0.0,9.0,0.0,0.0,5
20,20001713,2019-07-13,2019-07-26,5.0,1.0,0.0,0.0,27.0,0.0,0.0,14
21,20001788,2020-03-14,2020-03-23,7.0,4.0,0.0,15.0,32.0,3.0,0.0,10
22,20001800,2019-10-03,2019-12-17,231.0,12.0,4.0,115.0,293.0,42.0,2.0,76
23,20001820,2019-09-02,2019-09-16,54.0,5.0,0.0,8.0,62.0,4.0,0.0,15
24,20001949,2019-12-20,2020-01-31,129.0,21.0,2.0,124.0,148.0,25.0,1.0,43
25,20001981,2019-10-30,2019-11-03,3.0,1.0,0.0,7.0,18.0,0.0,0.0,5
26,20001988,2019-08-04,2019-08-12,13.0,4.0,0.0,18.0,37.0,2.0,0.0,9
27,20002159,2019-12-15,2020-01-29,94.0,11.0,0.0,134.0,192.0,38.0,1.0,46
28,20002216,2019-12-23,2020-02-06,245.0,12.0,3.0,120.0,203.0,36.0,1.0,46
29,20002248,2019-07-02,2019-07-14,13.0,3.0,0.0,0.0,20.0,0.0,0.0,13
...,...,...,...,...,...,...,...,...,...,...,...
134989,29997662,2019-07-05,2019-07-09,5.0,5.0,0.0,20.0,28.0,3.0,0.0,5
134990,29997728,2019-07-08,2019-10-03,27.0,7.0,0.0,9.0,167.0,2.0,3.0,88
134991,29997791,2019-12-21,2020-02-04,653.0,24.0,9.0,184.0,206.0,46.0,1.0,46
134992,29997838,2019-11-19,2019-11-19,2.0,0.0,0.0,4.0,7.0,0.0,0.0,1
134993,29997865,2019-12-08,2019-12-15,3.0,6.0,0.0,11.0,18.0,1.0,0.0,8
134994,29997978,2019-07-07,2019-09-20,84.0,7.0,1.0,311.0,326.0,75.0,2.0,76
134995,29998133,2019-07-12,2019-10-26,94.0,8.0,0.0,82.0,245.0,26.0,3.0,107
134996,29998158,2020-01-21,2020-01-22,1.0,2.0,0.0,7.0,7.0,0.0,0.0,2
134997,29998186,2020-03-26,2020-03-29,5.0,3.0,0.0,4.0,23.0,1.0,0.0,4
134998,29998441,2020-03-25,2020-04-20,3.0,2.0,0.0,0.0,8.0,0.0,1.0,27
134999,29998442,2019-09-12,2019-09-13,2.0,1.0,0.0,13.0,13.0,1.0,0.0,2
135000,29998599,2019-11-30,2020-02-13,268.0,18.0,0.0,303.0,326.0,56.0,2.0,76
135001,29998629,2020-03-10,2020-04-11,3.0,3.0,0.0,2.0,11.0,0.0,1.0,33
135002,29998711,2019-10-06,2019-10-07,2.0,3.0,0.0,11.0,11.0,2.0,0.0,2
135003,29998725,2019-08-19,2019-08-19,3.0,2.0,0.0,0.0,6.0,0.0,0.0,1
135004,29998731,2019-07-01,2019-10-15,196.0,21.0,14.0,214.0,326.0,70.0,3.0,107
135005,29998796,2019-11-03,2019-11-09,24.0,3.0,0.0,23.0,39.0,3.0,0.0,7
135006,29998835,2019-08-22,2019-10-06,175.0,4.0,0.0,204.0,206.0,44.0,1.0,46
135007,29999005,2019-09-26,2019-12-10,131.0,10.0,0.0,321.0,395.0,75.0,2.0,76
135008,29999052,2020-02-22,2020-03-11,4.0,2.0,0.0,2.0,33.0,0.0,1.0,19
135009,29999196,2019-07-06,2019-07-18,10.0,15.0,0.0,58.0,61.0,13.0,0.0,13
135010,29999206,2020-01-06,2020-02-20,280.0,15.0,1.0,205.0,206.0,45.0,1.0,46
135011,29999335,2020-02-05,2020-02-16,12.0,5.0,0.0,54.0,62.0,8.0,0.0,12
135012,29999524,2019-07-05,2019-07-09,4.0,2.0,0.0,2.0,12.0,0.0,0.0,5
135013,29999590,2020-01-21,2020-03-04,90.0,6.0,0.0,63.0,154.0,27.0,1.0,44
135014,29999740,2019-07-11,2019-07-25,15.0,3.0,0.0,11.0,31.0,0.0,0.0,15
135015,29999820,2019-09-22,2019-10-01,12.0,6.0,0.0,22.0,50.0,7.0,0.0,10
135016,29999822,2019-11-22,2019-12-03,5.0,4.0,0.0,2.0,25.0,1.0,0.0,12
135017,29999889,2019-08-23,2019-11-06,245.0,45.0,40.0,326.0,326.0,68.0,2.0,76
135018,29999945,2020-03-14,2020-04-23,36.0,2.0,0.0,131.0,166.0,27.0,1.0,41

In [110]:
column_list=[ 'app_opens', 'cust_service_mssgs', 'num_videos_rated', 'num_videos_completed',
                    'num_videos_more_than_30_seconds', 'num_series_started']
for col in column_list:
    Egm_data[col]=Egm_data[col]/Egm_data['days']

Egm_data.head()

,subid,day_min,day_max,app_opens,cust_service_mssgs,num_videos_rated,num_videos_completed,num_videos_more_than_30_seconds,num_series_started,payment_period_max,days
0,20000062,2019-06-30,2019-07-04,0.800000,0.600000,0.0,1.200000,4.600000,0.200000,0.0,5
1,20000405,2020-03-08,2020-03-18,0.454545,0.363636,0.0,1.181818,1.545455,0.090909,0.0,11
2,20000604,2020-02-09,2020-03-05,0.538462,0.192308,0.0,0.307692,2.615385,0.038462,1.0,26
3,20000685,2020-03-03,2020-04-15,1.045455,0.227273,0.0,0.318182,3.750000,0.181818,1.0,44
4,20000741,2019-08-25,2019-08-26,0.500000,0.500000,0.0,1.000000,3.500000,0.000000,0.0,2

In [111]:
Egm_data=Egm_data.drop(columns=['day_min', 'day_max'])
Egm_data.head()

,subid,app_opens,cust_service_mssgs,num_videos_rated,num_videos_completed,num_videos_more_than_30_seconds,num_series_started,payment_period_max,days
0,20000062,0.800000,0.600000,0.0,1.200000,4.600000,0.200000,0.0,5
1,20000405,0.454545,0.363636,0.0,1.181818,1.545455,0.090909,0.0,11
2,20000604,0.538462,0.192308,0.0,0.307692,2.615385,0.038462,1.0,26
3,20000685,1.045455,0.227273,0.0,0.318182,3.750000,0.181818,1.0,44
4,20000741,0.500000,0.500000,0.0,1.000000,3.500000,0.000000,0.0,2

In [112]:
df1.columns

Index(['subid', 'package_type', 'num_weekly_services_utilized',
       'preferred_genre', 'intended_use', 'weekly_consumption_hour',
       'num_ideal_streaming_services', 'retarget_TF', 'age', 'male_TF',
       'country', 'attribution_technical', 'attribution_survey', 'op_sys',
       'months_per_bill_period', 'plan_type', 'monthly_price',
       'discount_price', 'account_creation_date', 'creation_until_cancel_days',
       'cancel_before_trial_end', 'trial_end_date',
       'initial_credit_card_declined', 'revenue_net', 'join_fee', 'language',
       'paid_TF', 'refund_after_trial_TF', 'payment_type'],
      dtype='object')

In [113]:
#Merge 3 datasets:subscribers,customer_service_rep and engagement.
eng_csr=pd.merge(Egm_data,df2)
eng_csr.head()

,subid,app_opens,cust_service_mssgs,num_videos_rated,num_videos_completed,num_videos_more_than_30_seconds,num_series_started,payment_period_max,days,customer_service_rep_id,...,num_trial_days,trial_completed_TF,billing_channel,revenue_net_1month,payment_period,last_payment,next_payment,renew,month,year
0,20000062,0.800000,0.600000,0.0,1.200000,4.600000,0.200000,0.0,5,32881490,...,14,False,OTT,0.0000,0,2019-06-30 23:05:47,NaT,False,6,2019
1,20000405,0.454545,0.363636,0.0,1.181818,1.545455,0.090909,0.0,11,32055139,...,14,False,OTT,0.0000,0,2020-03-08 14:14:06,NaT,False,3,2020
2,20000604,0.538462,0.192308,0.0,0.307692,2.615385,0.038462,1.0,26,34802377,...,14,True,OTT,4.5875,1,2020-02-24 11:05:23,NaT,False,2,2020
3,20000685,1.045455,0.227273,0.0,0.318182,3.750000,0.181818,1.0,44,35600079,...,14,True,OTT,3.6700,1,2020-03-18 14:33:41,NaT,False,3,2020
4,20000741,0.500000,0.500000,0.0,1.000000,3.500000,0.000000,0.0,2,34671162,...,14,False,OTT,0.0000,0,2019-08-25 23:38:14,NaT,False,8,2019

In [114]:
sec=pd.merge(df1,eng_csr)
sec.head()

,subid,package_type,num_weekly_services_utilized,preferred_genre,intended_use,weekly_consumption_hour,num_ideal_streaming_services,retarget_TF,age,male_TF,...,num_trial_days,trial_completed_TF,billing_channel,revenue_net_1month,payment_period,last_payment,next_payment,renew,month,year
0,26844789,enhanced,3.362885,regional,replace OTT,36.001186,1.951776,False,25.0,True,...,14,False,OTT,0.0000,0,2019-12-07 17:34:29,NaT,False,12,2019
1,29726122,base,2.049135,comedy,access to exclusive content,20.051667,1.860289,False,61.0,False,...,14,True,OTT,4.5875,1,2020-03-05 13:52:53,NaT,False,2,2020
2,20299962,base,3.002048,drama,access to exclusive content,34.551230,1.870503,False,23.0,False,...,14,True,OTT,3.4498,1,2020-03-20 13:54:48,NaT,False,3,2020
3,24930568,base,NaN,comedy,access to exclusive content,25.851492,NaN,False,73.0,False,...,14,False,OTT,0.0000,0,2020-02-23 18:05:22,NaT,False,2,2020
4,21361112,enhanced,NaN,comedy,access to exclusive content,37.451142,NaN,False,24.0,True,...,14,False,OTT,0.0000,0,2019-12-01 08:05:17,NaT,False,12,2019

In [115]:
#Choose features for the model
sec_mdl=sec[['package_type','preferred_genre', 'intended_use','male_TF','attribution_technical','plan_type','op_sys','app_opens', 'cust_service_mssgs', 'num_videos_rated',
       'num_videos_completed', 'num_videos_more_than_30_seconds',
       'num_series_started', 'revenue_net','current_sub_TF']]

In [116]:
sec_mdl.head()

,package_type,preferred_genre,intended_use,male_TF,attribution_technical,plan_type,op_sys,app_opens,cust_service_mssgs,num_videos_rated,num_videos_completed,num_videos_more_than_30_seconds,num_series_started,revenue_net,current_sub_TF
0,enhanced,regional,replace OTT,True,organic,base_uae_14_day_trial,iOS,1.000000,1.000000,0.000000,6.500000,6.500000,0.500000,0.0000,False
1,base,comedy,access to exclusive content,False,bing,base_uae_14_day_trial,Android,0.869565,0.369565,0.130435,3.956522,3.956522,0.847826,4.5875,True
2,base,drama,access to exclusive content,False,email,base_uae_14_day_trial,iOS,2.260870,0.217391,0.000000,1.826087,4.478261,0.630435,3.4498,True
3,base,comedy,access to exclusive content,False,facebook,base_uae_14_day_trial,iOS,1.500000,1.500000,0.000000,1.000000,6.500000,0.000000,0.0000,False
4,enhanced,comedy,access to exclusive content,True,search,base_uae_14_day_trial,iOS,0.571429,0.428571,0.000000,0.285714,1.714286,0.000000,0.0000,False

In [117]:
sec_mdl['revenue_net'].mean()

1.708015078665189

In [118]:
sec_mdl['preferred_genre']=sec_mdl['preferred_genre'].fillna('Unknown')
sec_mdl['package_type']=sec_mdl['package_type'].fillna('Unknown')
sec_mdl['intended_use']=sec_mdl['intended_use'].fillna('Unknown')
sec_mdl['revenue_net']=sec_mdl['revenue_net'].fillna(1.71)

/Users/huyi/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
/Users/huyi/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

/Users/huyi/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/Users/huyi/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.

In [243]:
# Change categorical variables into binary variables
sec_mdl.loc[sec_mdl['current_sub_TF']==True,'current_sub_TF']=1
sec_mdl.loc[sec_mdl['current_sub_TF']==False,'current_sub_TF']=0

/Users/huyi/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:543: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s

In [244]:
sec_mdl.columns

Index(['package_type', 'preferred_genre', 'intended_use', 'male_TF',
       'attribution_technical', 'plan_type', 'op_sys', 'app_opens',
       'cust_service_mssgs', 'num_videos_rated', 'num_videos_completed',
       'num_videos_more_than_30_seconds', 'num_series_started', 'revenue_net',
       'current_sub_TF'],
      dtype='object')

In [245]:
# divid features into catergory and numerical
f_cat=['package_type', 'preferred_genre', 'intended_use', 'male_TF',
       'attribution_technical', 'plan_type', 'op_sys']
f_num=['app_opens',
       'cust_service_mssgs', 'num_videos_rated', 'num_videos_completed',
       'num_videos_more_than_30_seconds', 'num_series_started', 'revenue_net']
for i in f_cat:
    sec_mdl[i].astype('category')

# convert catergory features into dummy variables
def change_to_dummies(df):
    dm_df= pd.DataFrame()
    for i in f_cat:
        dm_df=pd.concat([dm_df,pd.get_dummies(df[i],prefix=i, drop_first=True)],axis=1)
    for j in f_num:
        dm_df[j]=df[j]
    dm_df=pd.concat([dm_df, df['current_sub_TF']], axis=1)
    return dm_df

In [246]:
#Split data into training (70%) and test (30%) data set
from sklearn.model_selection import train_test_split

from matplotlib.colors import ListedColormap

from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import validation_curve

from sklearn.model_selection import GridSearchCV
dm_mdl=change_to_dummies(sec_mdl)
X=dm_mdl.drop(['current_sub_TF'], axis=1)
y=dm_mdl['current_sub_TF']
X_train, X_test, y_train, y_test=train_test_split(X,y, test_size=0.3, random_state=42)

In [247]:
X_train.columns

Index(['package_type_base', 'package_type_economy', 'package_type_enhanced',
       'preferred_genre_comedy', 'preferred_genre_drama',
       'preferred_genre_international', 'preferred_genre_other',
       'preferred_genre_regional', 'intended_use_access to exclusive content',
       'intended_use_education', 'intended_use_expand international access',
       'intended_use_expand regional access', 'intended_use_other',
       'intended_use_replace OTT', 'intended_use_supplement OTT',
       'male_TF_True', 'attribution_technical_appstore',
       'attribution_technical_bing', 'attribution_technical_bing_organic',
       'attribution_technical_brand sem intent bing',
       'attribution_technical_brand sem intent google',
       'attribution_technical_content_greatist',
       'attribution_technical_criteo', 'attribution_technical_direct_mail',
       'attribution_technical_discovery', 'attribution_technical_display',
       'attribution_technical_email', 'attribution_technical_email_blast',
       'attribution_technical_facebook',
       'attribution_technical_facebook_organic',
       'attribution_technical_google_organic',
       'attribution_technical_influencer', 'attribution_technical_internal',
       'attribution_technical_organic', 'attribution_technical_other',
       'attribution_technical_ott', 'attribution_technical_pinterest',
       'attribution_technical_pinterest_organic',
       'attribution_technical_playstore', 'attribution_technical_podcast',
       'attribution_technical_quora', 'attribution_technical_referral',
       'attribution_technical_samsung', 'attribution_technical_search',
       'attribution_technical_tv', 'attribution_technical_twitter',
       'attribution_technical_vod', 'attribution_technical_youtube',
       'plan_type_base_uae_14_day_trial',
       'plan_type_base_uae_no_trial_7_day_guarantee',
       'plan_type_high_aud_14_day_trial', 'plan_type_high_jpy_14_day_trial',
       'plan_type_high_sar_14_day_trial', 'plan_type_high_uae_14_day_trial',
       'plan_type_low_gbp_14_day_trial', 'plan_type_low_uae_no_trial',
       'op_sys_iOS', 'app_opens', 'cust_service_mssgs', 'num_videos_rated',
       'num_videos_completed', 'num_videos_more_than_30_seconds',
       'num_series_started', 'revenue_net'],
      dtype='object')

2.Logistic Model

In [248]:
from sklearn.metrics import auc, classification_report, f1_score, confusion_matrix, accuracy_score, roc_auc_score, roc_curve
clf = LogisticRegression(C=100).fit(X_train,y_train)
y_prob_predicted = clf.predict(X_test)
print('Accuracy of Logistic regression classifier on training set: {:.5f}'
     .format(clf.score(X_train, y_train)))

print('Accuracy of Logistic regression classifier on test set: {:.5f}'
     .format(clf.score(X_test, y_test)))
print(classification_report(y_test,y_prob_predicted))

/Users/huyi/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

Accuracy of Logistic regression classifier on training set: 0.86703
Accuracy of Logistic regression classifier on test set: 0.86570
              precision    recall  f1-score   support

           0       0.90      0.93      0.91     30806
           1       0.75      0.65      0.70      9700

   micro avg       0.87      0.87      0.87     40506
   macro avg       0.82      0.79      0.81     40506
weighted avg       0.86      0.87      0.86     40506

In [250]:
importance = pd.DataFrame(clf.coef_[0], index = X_train.columns, columns=['coefficents'])
importance.sort_values(by=['coefficents'])

                                               coefficents
intended_use_expand international access         -5.655109
intended_use_expand regional access              -5.565570
intended_use_education                           -5.380405
plan_type_high_uae_14_day_trial                  -4.576167
intended_use_other                               -3.702860
intended_use_supplement OTT                      -2.984016
intended_use_replace OTT                         -2.684764
attribution_technical_quora                      -2.475312
intended_use_access to exclusive content         -2.370500
attribution_technical_content_greatist           -2.146371
attribution_technical_discovery                  -2.123949
cust_service_mssgs                               -1.594863
attribution_technical_pinterest_organic          -1.406786
attribution_technical_internal                   -1.259260
attribution_technical_influencer                 -0.854803
attribution_technical_direct_mail                -0.807795
attribution_technical_facebook_organic           -0.757247
attribution_technical_bing_organic               -0.650753
attribution_technical_email_blast                -0.460331
attribution_technical_brand sem intent bing      -0.426456
attribution_technical_criteo                     -0.396349
attribution_technical_other                      -0.327154
attribution_technical_pinterest                  -0.244928
num_videos_more_than_30_seconds                  -0.205104
male_TF_True                                     -0.201769
plan_type_high_aud_14_day_trial                  -0.167445
num_videos_completed                             -0.088011
plan_type_high_sar_14_day_trial                  -0.029339
plan_type_high_jpy_14_day_trial                  -0.026958
attribution_technical_twitter                    -0.013404
...                                                    ...
attribution_technical_ott                         0.102224
attribution_technical_samsung                     0.140144
attribution_technical_vod                         0.177461
attribution_technical_podcast                     0.181737
attribution_technical_google_organic              0.301008
plan_type_base_uae_14_day_trial                   0.318358
attribution_technical_display                     0.319636
attribution_technical_brand sem intent google     0.321827
op_sys_iOS                                        0.490054
attribution_technical_search                      0.493181
attribution_technical_email                       0.536787
attribution_technical_youtube                     0.538027
attribution_technical_referral                    0.577147
preferred_genre_other                             0.605287
attribution_technical_facebook                    0.611526
preferred_genre_regional                          0.656198
attribution_technical_organic                     0.721288
revenue_net                                       0.884920
preferred_genre_international                     0.920743
preferred_genre_drama                             1.539477
num_series_started                                1.605936
plan_type_low_uae_no_trial                        1.607074
attribution_technical_playstore                   1.730331
preferred_genre_comedy                            1.849139
package_type_economy                              2.226270
attribution_technical_appstore                    2.463937
num_videos_rated                                  2.477025
package_type_enhanced                             2.521682
plan_type_base_uae_no_trial_7_day_guarantee       2.686381
package_type_base                                 2.827270

[64 rows x 1 columns]

2.Decision Tree

In [240]:
from sklearn.tree import DecisionTreeClassifier
clf2 = DecisionTreeClassifier(max_depth = 3).fit(X_train, y_train)

print('Accuracy of Decision Tree classifier on training set: {:.8f}'
     .format(clf2.score(X_train, y_train)))
print('Accuracy of Decision Tree classifier on test set: {:.8f}'
     .format(clf2.score(X_test, y_test)))

Accuracy of Decision Tree classifier on training set: 0.82156952
Accuracy of Decision Tree classifier on test set: 0.82140917

In [241]:
importance1 = pd.DataFrame(clf2.feature_importances_, index = X_train.columns, columns=['feature_importances_'])
importance1.sort_values(by=['feature_importances_'])
importance1.to_csv('coe_dt.csv')

3. Random Forest

In [234]:
from sklearn.ensemble import RandomForestClassifier


clf3 = RandomForestClassifier(max_depth = 7,n_estimators=20).fit(X_train, y_train)
print('Accuracy of Random Forest classifier on training set: {:.8f}'
     .format(clf3.score(X_train, y_train)))
print('Accuracy of Random Forest classifier on test set: {:.8f}'
     .format(clf3.score(X_test, y_test)))

Accuracy of Random Forest classifier on training set: 0.81258663
Accuracy of Random Forest classifier on test set: 0.80751000

In [242]:
importance2 = pd.DataFrame(clf3.feature_importances_, index = X_train.columns, columns=['feature_importances_'])
importance2.sort_values(by=['feature_importances_'])
importance2.to_csv('co_rf.csv')

# CLV

In [211]:
# For each subid, macth the cac calculted before
cac_set=sec.merge(ad_m,on=['year','month','attribution_technical'],how='left')

cac_set['CAC']=cac_set['CAC'].fillna(0)
cac_set.head()

,subid,package_type,num_weekly_services_utilized,preferred_genre,intended_use,weekly_consumption_hour,num_ideal_streaming_services,retarget_TF,age,male_TF,...,revenue_net_1month,payment_period,last_payment,next_payment,renew,month,year,num_users,spend,CAC
0,26844789,enhanced,3.362885,regional,replace OTT,36.001186,1.951776,False,25.0,True,...,0.0000,0,2019-12-07 17:34:29,NaT,False,12,2019,NaN,NaN,0.000000
1,29726122,base,2.049135,comedy,access to exclusive content,20.051667,1.860289,False,61.0,False,...,4.5875,1,2020-03-05 13:52:53,NaT,False,2,2020,NaN,NaN,0.000000
2,20299962,base,3.002048,drama,access to exclusive content,34.551230,1.870503,False,23.0,False,...,3.4498,1,2020-03-20 13:54:48,NaT,False,3,2020,11259.262866,78000.0,6.927629
3,24930568,base,NaN,comedy,access to exclusive content,25.851492,NaN,False,73.0,False,...,0.0000,0,2020-02-23 18:05:22,NaT,False,2,2020,22134.740620,49700.0,2.245339
4,21361112,enhanced,NaN,comedy,access to exclusive content,37.451142,NaN,False,24.0,True,...,0.0000,0,2019-12-01 08:05:17,NaT,False,12,2019,8676.928664,32100.0,3.699466

In [212]:
# Add the probability of churn in dataset
pre=clf2.predict_proba(X_test)
pre=pd.DataFrame(pre)
pre.head()
pre.shape

(40506, 2)

In [213]:
actual=pd.DataFrame(y_test)
actual.head(10)
actual.shape

(40506, 1)

In [214]:
table_tst=pre.join(actual.reset_index())
table_tst.head(10)

          0         1   index  current_sub_TF
0  0.325478  0.674522   71411               0
1  0.456358  0.543642   83708               1
2  0.325478  0.674522   61244               1
3  0.949072  0.050928    2029               0
4  0.949072  0.050928   73561               0
5  0.949072  0.050928   82568               0
6  0.949072  0.050928   11307               0
7  0.325478  0.674522  132616               1
8  0.789078  0.210922   87830               0
9  0.325478  0.674522    6559               1

In [228]:
r_sec=pd.DataFrame(cac_set[['subid','attribution_technical','monthly_price','month','year','CAC']]).reset_index()
df_churn=pd.merge(table_tst,r_sec)
df_churn.head()

,0,1,index,current_sub_TF,subid,attribution_technical,monthly_price,month,year,CAC
0,0.325478,0.674522,71411,0,22516965,brand sem intent google,4.7343,8,2019,4.847342
1,0.456358,0.543642,83708,1,27925605,email,4.7343,3,2020,6.927629
2,0.325478,0.674522,61244,1,26089638,facebook,4.7343,12,2019,2.442401
3,0.949072,0.050928,2029,0,20656846,brand sem intent google,4.7343,8,2019,4.847342
4,0.949072,0.050928,73561,0,28762470,search,4.7343,2,2020,2.475687

In [229]:
# Calculate CLV for each id
# Since we set the annual discount rate as 10%, and users have to pay 3 times a year(every 4 months)
#Formula: payment[i]*(1+r)/(1+r-prb(churn))-cac
r= 0.1/3
df_churn['CLV']=df_churn['monthly_price']*(1+r)/(1+r-df_churn[0])-df_churn['CAC']
df_churn.head()

,0,1,index,current_sub_TF,subid,attribution_technical,monthly_price,month,year,CAC,CLV
0,0.325478,0.674522,71411,0,22516965,brand sem intent google,4.7343,8,2019,4.847342,2.063834
1,0.456358,0.543642,83708,1,27925605,email,4.7343,3,2020,6.927629,1.551257
2,0.325478,0.674522,61244,1,26089638,facebook,4.7343,12,2019,2.442401,4.468775
3,0.949072,0.050928,2029,0,20656846,brand sem intent google,4.7343,8,2019,4.847342,53.211105
4,0.949072,0.050928,73561,0,28762470,search,4.7343,2,2020,2.475687,55.582760

In [253]:
df_churn.to_csv('CLV.csv')
df_churn['CLV'].describe()

count    40506.000000
mean        31.116066
std         22.987391
min        -50.573506
25%          8.478887
50%         20.028711
75%         55.381694
max         61.145700
Name: CLV, dtype: float64